#!/bin/sh

# install
if [ -d "/mnt/SDCARD/miyoo" ] ; then
	exit 0
fi

# or launch (and keep launched)
LAUNCH_PATH="/mnt/SDCARD/.system/paks/MiniUI.pak/launch.sh"
while [ -f "$LAUNCH_PATH" ] ; do
	"$LAUNCH_PATH"
done

reboot # under no circumstances should stock be allowed to touch this card