#!/bin/sh

SDCARD_PATH="/mnt/SDCARD"
LAUNCH_PATH="$SDCARD_PATH/.system/paks/MiniUI.pak/launch.sh"
INSTALL_DIR="$SDCARD_PATH/miyoo"

# install
if [ -d "$INSTALL_DIR" ] ; then
	exit 0
fi

# or launch (and keep launched)
while [ -f "$LAUNCH_PATH" ] ; do
	"$LAUNCH_PATH"
done

reboot # under no circumstances should stock be allowed to touch this card