#!/bin/bash

cd ./third-party/picoarch

shopt -s dotglob

update() {
    for d in "$@"; do
        test -d "$d" -a \! -L "$d" || continue
        cd "$d"
        if [ -d ".git" ]; then
            echo "$(git rev-parse --short HEAD) $(basename $PWD)"
        else
            update *
        fi
        cd ..
    done
}

update *

echo "-------"
echo "generated by $0"